### ISSUE TITLE
backend + api + websockets

### ISSUE THREAD

**Issue by vinnitu** [caoxiemeihao/electron-vue-vite#6]
Hi!

My backend (express + ws) serves static vite3 app (fetch api + websockets).

Now I want make standalone solution with electron.

I want use your template as basis.

But I have many questions.

I think better use http over unix-sock instread of tcp but I don't sure renderer can interact with main process with unix+http:// protocol. 

```
const socket = new WebSocket('unix+ws://tmp/sock')
```

Main idea is seamless support source code main project (web version) and standalone (elecron).

Or maybe use some of function electron

```
protocol.intercept... ('ws', (request, callback))
```

Do you understand what I mean?

**Comment by caoxiemeihao** [comment]
1. 主进程与渲染进程通信的最佳方式依然是内置的 ipc 管道
2. 如果考虑用 socket 的话，估计 websocket 首选

因为渲染进程使用 NodeAPI 总有些奇奇怪怪 BUG，尤其是异步 API

---

1. The best way for the main process to communicate with the renderer process is still through the built-in IPC pipeline
2. If Socket is considered, WebSocket is preferred

Because there are always some weird bugs with the NodeAPI for renderers, especially asynchronous APIs
